#!/bin/bash

function update {
	sudo rm -rf "/usr/games/retro"
	python3 dofus_retro_updater.py
	sudo mv retro "/usr/games"
	# Adding Icons and .desktop file
	echo "[+] Adding Desktop Shortcut Icon..."
	wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.icns"
	sudo mv "Dofus Retro.icns" "/usr/games/retro"
	wget "https://github.com/adann0/dofus_retro_updater/raw/main/Dofus%20Retro.desktop"
	if [[ -d "/home/$USER/Desktop" ]]
	then
		sudo mv "Dofus Retro.desktop" "/home/$USER/Desktop"
	elif [[ -d "/home/$USER/Bureau" ]]
	then
		sudo mv "Dofus Retro.desktop" "/home/$USER/Bureau"
	else
		echo "[-] Unable to find your Desktop. You can move 'Dofus Retro.desktop' file to your Desktop if you want a Shortcut."
	fi
	echo "[+] OK."
}

function uninstall {
	echo "[+] Removing all files..."
	sudo rm -rf "/usr/games/retro"
	rm -rf "/home/$USER/.config/Dofus Retro"
	echo "[+] OK."
}

echo "*** DOFUS RETRO UPDATER for Linux ***"

if [[ $1 == "update" ]] 
then
	update
elif [[ $1 == "uninstall" ]]
then
	uninstall
else
	echo "USAGE: ./dofus_retro_updater [update|uninstall]"
	exit
fi

echo "[+] ALL DONE."
