#!/bin/bash

function update {
	sudo rm -rf "/usr/games/retro"
	python3 dofus_retro_updater.py
	sudo mv retro "/usr/games"
}

function uninstall {
	sudo rm -rf "/usr/games/retro"
	rm -rf "/home/$USER/.config/Dofus Retro"
}

if [[ $1 == "update" ]] 
then
	update
elif [[ $1 == "uninstall" ]]
then
	uninstall
else
	echo "USAGE: ./dofus_retro_updater [update|uninstall]"
	exit
fi

echo "[+] ALL DONE."